#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50



start() {
	config_load busybox
	config_get enable telnet enable
	if [ x"$enable" = x"1" ]; then
		service_start /usr/sbin/telnetd -l /bin/login.sh
	fi
}

stop() {
	service_stop /usr/sbin/telnetd
}
